### ISSUE TITLE
Alloy compiler failed (cannot find module <project>/undefined)

### ISSUE THREAD

**Issue by jasonshark** [appcelerator/titanium#226]
I have a titanium mobile project. I am trying to run it from the command line. I do:

```
$ npm install titanium -g
$ titanium sdk install 3.5.0.GA
$ titanium build --platform=iphone
```

and I get this error:

```
[INFO]  Deploy type: development
[INFO]  Building for target: simulator
[INFO]  Building using iOS SDK: 8.2
[INFO]  Building for iOS Simulator: iPhone 4s
[DEBUG] UDID: F0598C60-FAF3-414E-8333-E4124DDC177A
[DEBUG] Simulator type: iphone
[DEBUG] Simulator version: 8.2
[INFO]  Building for device family: universal
[DEBUG] Setting Xcode target to Debug
[DEBUG] Setting Xcode build OS to iphonesimulator8.2
[DEBUG] Xcode installation: /Applications/Xcode.app/Contents/Developer
[DEBUG] iOS WWDR certificate: installed
[INFO]  Minimum iOS version: 7.0
[INFO]  Debugging disabled
[INFO]  Profiler disabled
[INFO]  Forcing rebuild: /Users/connorleech/Proteus/app-ti-pasteboardWriter/build/iphone/build-manifest.json does not exist
[INFO]  Initiating prepare phase
[INFO]  Found Alloy app in /Users/connorleech/Proteus/app-ti-pasteboardWriter/app
[INFO]  Executing Alloy compile: /usr/local/bin/node  compile /Users/connorleech/Proteus/app-ti-pasteboardWriter/app --config platform=ios,version=0,simtype=none,devicefamily=universal,deploytype=development,target=simulator
[DEBUG] module.js:340
[DEBUG]     throw err;
[DEBUG]           ^
[ERROR] : Cannot find module '/Users/connorleech/Proteus/app-ti-pasteboardWriter/undefined'
[DEBUG]     at Function.Module._resolveFilename (module.js:338:15)
[DEBUG]     at Function.Module._load (module.js:280:25)
[DEBUG]     at Function.Module.runMain (module.js:497:10)
[DEBUG]     at startup (node.js:119:16)
[DEBUG]     at node.js:906:3
[ERROR] Alloy compiler failed
```

I want to run the app in my iOS simulator. Running it on an ipad simulator would be best. What am I doing wrong?

**Comment by cb1kenobi** [comment]
That sounds like a bug in https://github.com/appcelerator/alloy, not the Titanium CLI. Please file a ticket here: https://jira.appcelerator.org.

**Comment by IAmJulianAcosta** [comment]
try 
```
npm install titanium -g
```

**Comment by Cdvalencia** [comment]
Gracias!! @IAmJulianAcosta
